# Generated by Django 5.2.6 on 2026-02-12 15:22

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(db_index=True, max_length=150)),
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ViajeOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('ciudad_salida', models.CharField(max_length=150)),
                ('ciudad_llegada', models.CharField(max_length=150)),
                ('plazas_disponibles', models.IntegerField()),
                ('hora', models.TimeField()),
                ('acepto_mascotas', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=2)),
                ('regreso_hoy', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=2)),
                ('nombre_sector', models.CharField(max_length=30)),
                ('nivel_escalada', models.CharField(max_length=5)),
                ('descripcion_viaje', models.CharField(blank=True, max_length=350, null=True)),
                ('propietario_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_plazas', models.IntegerField()),
                ('estado', models.CharField(choices=[('Aceptada', 'Aceptada'), ('Pendiente', 'Pendiente'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=10)),
                ('fecha_hora_solicitud', models.DateTimeField(auto_now_add=True)),
                ('quien_solicita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_solicitada', to='usuarios.perfil')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.viajeoferta')),
            ],
            managers=[
                ('objecst', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_plazas', models.IntegerField()),
                ('quien_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='viajes.viajeoferta')),
            ],
        ),
    ]
