# Generated by Django 5.2.6 on 2026-03-17 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='solicitud',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='quien_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='viaje',
        ),
        migrations.AddField(
            model_name='reserva',
            name='solicitud',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='viajes.solicitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_plazas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='numero_plazas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'Pendiente')), fields=('quien_solicita', 'viaje'), name='unica_solicitud_por_usuario_edo_pendiente'),
        ),
    ]
