"""
Django settings for CuerdApp project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


#Necesarioo para cargar variables de entorno
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iztt9@p099j=cd&xl!(k%f%$p)+ec1f9wdi6&n4s1ulhl$0b40'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.Core',
    'inscripcion_newsletter.apps.InscripcionNewsletterConfig',
    'usuarios.apps.UsuariosConfig',
    'viajes.apps.ViajesConfig',
    'phonenumber_field',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'CuerdApp.middleware.tiene_perfil.TienePerfilMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'CuerdApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['C:/Users/USUARIO/Desktop/PyCharmProjects/ProyectoFinal/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'inscripcion_newsletter.context_processors.newsletter_form',
                'viajes.context_processors.revisar_solicitudes'
            ],
        },
    },
]

WSGI_APPLICATION = 'CuerdApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Cnfiguración para utilizar PostgresQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME',None),
        'USER': os.getenv('DB_USER',None),
        'PASSWORD': os.getenv('DB_PASSWORD',None),
        'HOST': '127.0.0.1',
        'PORT': '5432'
    }
}

#Aviso de falta de variables de entorno
db_name = os.getenv('DB_NAME')
db_user = os.getenv('DB_USER')
db_password = os.getenv('DB_PASSWORD')

if not db_name or not db_user or not db_password:
    print(
        "⚠️ Las variables de entorno DB_NAME, DB_USER o DB_PASSWORD no están definidas.\n"
        "La base de datos no se podrá conectar hasta que se completen estas variables."
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Configuraciones propias del proyecto en desarrollo

# Configuración para poder enviar emails

EMAIL_BACKEND= 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST= 'smtp.gmail.com'
EMAIL_USE_TLS= True
EMAIL_PORT= 587
EMAIL_HOST_USER= os.getenv('EMAIL_HOST_USER',None)
EMAIL_HOST_PASSWORD= os.getenv('EMAIL_HOST_PASSWORD',None)
DEFAULT_FROM_EMAIL= 'Soporte CuerdApp <contacto@cuerdapp.com>'


# Aviso por falta de credenciales
if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    print(
        "⚠️ EMAIL_HOST_USER o EMAIL_HOST_PASSWORD no definidas en las variables de entorno.\n"
        "Esto significa que NO se podrán enviar emails de confirmación de cuenta, "
        "restablecimiento de contraseña ni formularios desde la app."
    )

#Configuraciones para django-allauth

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_EMAIL_VERIFICATION_SUPPORTS_RESEND = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

AUTH_USER_MODEL = 'usuarios.Usuario'


# Configuración para usar Google OAuth 2.0
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID',None),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET',None),
            'key': ''
        }
    }
}

# Aviso en consola en caso de no haber variables de entorno
client_id = os.getenv('GOOGLE_CLIENT_ID')
client_secret = os.getenv('GOOGLE_CLIENT_SECRET')

if not client_id or not client_secret:
    print(" ⚠️Variables GOOGLE_CLIENT_ID y GOOGLE_CLIENT_SECRET no definidas.")
    print(" ⚠️La autenticación con Google estará desactivada.")


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",  # new
]

SITE_ID = 1

#Configuración django-allauth

ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_SIGNUP_FORM_CLASS = 'usuarios.forms.CustomSignupForm'



