# Generated by Django 5.2.6 on 2026-02-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailNewsletter',
            new_name='InscripcionNewsletter',
        ),
    ]
